# 1 for computational stress, 2 for IO stress
workload_type: 1

# whether the latency displays chrono correlations
is_time_series: false

# the expected latency in ms
expected_latency_ms: 7

frequency_ms: 10

# The higher, the prior
priority: 4