# Elements in tasks are objects
# Yuting@2022.12.30: no need to name tasks, just specify the type
tasks:
  - task_name: DummyTask
    config_file: dummy_task.yaml
  - task_name: DummyTask2
    config_file: dummy_task_2.yaml
  - task_name: DummyTask3
    config_file: dummy_task_3.yaml

num_workers: 4

# The smaller, the prior, range is 1 -> x
priority_range: 4

scheduler: DynamicScheduler