# Elements in task are objects
# Yuting@2022.12.30: no need to name task, just specify the type
tasks:

  - type: DummyTask
    name: dummy_task_1_1
    in_pipe_names: [ ]
    out_pipe_names: [ "dummy_pipe_1" ]
    config_file: dummy_task.yaml

  - type: DummyTask
    name: dummy_task_1_2
    in_pipe_names: [ ]
    out_pipe_names: [ "dummy_pipe_1" ]
    config_file: dummy_task.yaml

  - type: DummyTask2
    name: dummy_task_2_1
    in_pipe_names: [ ]
    out_pipe_names: [ "dummy_pipe_2" ]
    config_file: dummy_task_2.yaml

  - type: DummyTask2
    name: dummy_task_2_2
    in_pipe_names: [ ]
    out_pipe_names: [ "dummy_pipe_2" ]
    config_file: dummy_task_2.yaml

  - type: DummyTask3
    name: dummy_task_3_1
    in_pipe_names: [ "dummy_pipe_1", "dummy_pipe_2" ]
    out_pipe_names: [ ]
    config_file: dummy_task_3.yaml

num_workers: 4

# The smaller, the prior, range is 1 -> x
priority_range: 4

scheduler: DummyScheduler